name: Terraform Apply

on:
  push:
    branches: [ "master" ]
    paths:
      - terraform/**

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: production   # enables manual approval if you want

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
